image: gitpod/workspace-dotnet

ports:
  - port: 8000
  - port: 8080
    onOpen: ignore

tasks:
  - init: npm install
    command: npm run build-docs && npm start

github:
  prebuilds:
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true

vscode:
  extensions:
    - christian-kohler.path-intellisense
    - wayou.vscode-todo-highlight
    - mrmlnc.vscode-scss
    - Ionide.Ionide-fsharp
