name: CI
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Package restore
        run: npm install
      - name: Build docs
        run: npm run build-docs
      - name: Build site
        run: npm run build
